### ISSUE TITLE
Check for canceled courses

### ISSUE THREAD

**Issue by jdavalos1** [ucsb-cs48-w19/6pm-ucsb-rooms#21]
Check column 4 for the canceled courses when adding room numbers to ignore those in scrapping. Use keyword 'Cancelled' in scraper.

**Comment by agprice** [comment]
@jdavalos1 I believe this issue was solved with pull request https://github.com/ucsb-cs48-w19/6pm-ucsb-rooms/pull/25. Could you confirm and close the issue if so?
