### ISSUE TITLE
create postgress database

### ISSUE THREAD

**Issue by ryangormley81** [ucsb-cs48-w19/6pm-ucsb-rooms#9]
- [x] research how to do this, using Heroku

- [x] create sample data to add to base on a static file in the form of objects

- [x] upload objects to data base

- [x] crud functionality

**Comment by kissmax** [comment]
Mentor Approved

**Comment by pconrad** [comment]
Hi Everyone: Please when you have something in the "done" column, put a link to the pull request that addresses the issue.

**Comment by ryangormley81** [comment]
successfully connect, migrate with postgres db and push it to heroku
creating an new issue for SQLAlchemy data model IAW project

**Comment by yulunchan** [comment]
starting a new issue for data model
tailoring it to meet the app function requirements

**Comment by ryangormley81** [comment]
have not finished CRUD yet

**Comment by agprice** [comment]
A basic dummy database was initialized in pull request #15

**Comment by agprice** [comment]
The full database was created in pull request https://github.com/ucsb-cs48-w19/6pm-ucsb-rooms/pull/25.
